file added
IndianOpenSourceFoundation/dynamic-cli pull request #164
Opened 2022-03-06 16:35 UTC by saidhanya18

## Related Issue

I have added windows guidelines for the user

Closes: #[issue number that will be closed through this PR]

## Describe the changes you've made

## Checklist:

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

2022-03-06 16:44 UTC, GouravSardana requested changes
Please make the suggested changes

2022-03-06 16:44 UTC, GouravSardana commented on Window_setup.txt
> +2. https://docs.microsoft.com/en-us/windows/wsl/install
Can you use hyperlink and add those links there. One more thing link this file in the readme where we are giving instructions for windows user

2022-03-06 18:04 UTC, pranavbaburaj requested changes

2022-03-06 18:04 UTC, pranavbaburaj commented on Window_setup.txt
> +3. after that instal python3 using pip ($ sudo apt-get install python3-pip)
typos 🤖

2022-03-07 11:59 UTC, saidhanya18 commented on Window_setup.txt
> +3. after that instal python3 using pip ($ sudo apt-get install python3-pip)
issue solved

2022-03-07 12:03 UTC, pranavbaburaj requested changes
- Rename `Window_setup` to something like `windows_setup`.
- Use markdown file instead of text file, and use proper markdown elements like codeblocks and links.

2022-03-07 12:03 UTC, GouravSardana commented
cc @pranavbaburaj @PradyumnaKrishna @peb-peb

2022-03-07 16:00 UTC, GouravSardana commented on Window_setup.txt
> +3. after that install python3 using pip ($ sudo apt-get install python3-pip)
What if we don’t have python3-pip

2022-03-07 18:19 UTC, peb-peb commented
I think that there should no separate Documentation for setting WSL because after installing and setting up WSL, the procedure/steps to setup `dynamic-cli` in it is basically the same as linux. So, just referring to the WSL documentation should be enough in this case.

But, when `dynamic-cli` is available on WINDOWS, then maybe we could have it's separate _documentation_.

2022-03-07 18:38 UTC, pranavbaburaj commented
> I think that there should no **separate** Documentation for setting WSL because after installing and setting up WSL, the procedure/steps to setup `dynamic-cli` in it is basically the same as linux. So, just referring to the WSL documentation should be enough in this case.
> 
> But, when `dynamic-cli` is available on **WINDOWS**, then maybe we could have it's separate _documentation_.

hmm yeah, that sounds reasonable.

2022-03-07 18:50 UTC, peb-peb commented
So, if everyone agrees with it, then maybe we could close this PR.

@saidhanya18 I'll create a issue regarding this, and then you could follow from there.

2022-03-07 19:12 UTC, pranavbaburaj commented
Yes, I think we can also hear from @GouravSardana and @saidhanya18 before closing this

2022-03-07 19:33 UTC, GouravSardana commented
> no **separate** Documentation for setting

Sounds good but We need at least a document where we'll give the steps to install WSL

2022-03-07 20:27 UTC, peb-peb commented
> We need at least a document where we'll give the steps to install WSL

We could do that, so that new contributors are _not_ confused and could follow the commands directly. But the WSL installation documentation is very detailed in itself and most of the other open-source projects direct their contributors to their site.

So, I think it's a matter of preference. @GouravSardana @pranavbaburaj I would like to know your opinions on this.

2022-03-08 02:58 UTC, saidhanya18 commented
> So, if everyone agrees with it, then maybe we could close this PR.
> 
> @saidhanya18 I'll create a issue regarding this, and then you could follow from there.

sounds good !

2022-03-09 11:12 UTC, GouravSardana commented
Merging the PR. Adding the change now.

2022-03-09 11:13 UTC, merged