Add Arguments Guide to the README file
IndianOpenSourceFoundation/dynamic-cli pull request #52
Opened 2021-03-22 17:01 UTC by aaryanrr

Closes: #51 

#### Describe the changes you've made
1. The Documentation for the arguments that can be passed on to the CLI has been added to the README file
2. Some Typos in the README were fixed
3. Added the `alt` parameter to the `<img>` tag in the CONTRIBUTORS section of the README

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

Updated:
1. Documentation in the README

![image](https://user-images.githubusercontent.com/73213670/112027469-31e14b80-8b5d-11eb-8621-bcf72c608cd6.png)

2. `alt` parameter in the `<img>` tag

![image](https://user-images.githubusercontent.com/73213670/112028115-d9f71480-8b5d-11eb-8029-7992db0358c0.png)

2021-03-23 05:18 UTC, anshsrtv requested changes
Nice work 🎉  But a better way of doing the same has been given in the linked issue. Please consider it for your reference.

> ## Usage
> ```
> Usage: Dynamic [OPTIONS]
> 
> A Modern, user-friendly command-line HTTP client for the API testing, and if you're stuck - Search and browse StackOverflow without leaving the CLI.
> 
> Options:
>   -v, --version                 gives the version of our CLI
>   -s, --search                  Search a question on StackOverflow
>  -d,  --debug                   Turn on debugging mode
>   --help                        Show this message and exit.
> ```

2021-03-23 05:18 UTC, anshsrtv commented on README.md
> +### Credit goes to these peoples:✨
```suggestion
### Credit goes to these people:✨
```

2021-03-23 07:11 UTC, aaryanrr commented
@anshsrtv I'll do it according to that. Thanks for reviewing.

2021-03-24 04:52 UTC, aaryanrr commented
@anshsrtv Please have a look at this now!

2021-03-24 05:05 UTC, merged