Readme updated
IndianOpenSourceFoundation/dynamic-cli pull request #69
Opened 2021-03-31 09:13 UTC by anirudhsai20

## Related Issue
Readme file enhancement

Closes: #68 

## Describe the changes you've made
I have added a list of all the Open Source programs in which this project has been listed in. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

![dcli](https://user-images.githubusercontent.com/63279440/113120652-70e36100-922f-11eb-8041-7a1cf6f3396e.png)

2021-03-31 09:27 UTC, honeybhardwaj approved these changes
LGTM!!

2021-03-31 11:06 UTC, Siddhant-K-code requested changes

2021-03-31 11:06 UTC, Siddhant-K-code commented on README.md
> +## Dynamic CLI is a part of these open source programs:
Don’t add a trailing `:` to headings

2021-03-31 11:55 UTC, GouravSardana commented
@anirudhsai20 Don't you think this image is really very big for ReadME?

2021-03-31 11:57 UTC, anirudhsai20 commented
Ok. I will reduce the size of the image.

2021-03-31 11:59 UTC, anirudhsai20 commented
I have reduced the size of the image. Is this fine or do you want it to be smaller?

2021-04-01 05:34 UTC, GouravSardana commented
@anirudhsai20 Can you please fix this one check. So that I can merge

2021-04-01 07:01 UTC, anirudhsai20 commented
I hope the issue is fixed now.

2021-04-01 07:41 UTC, merged