:rocket: Add Notion.so login feature to get token
IndianOpenSourceFoundation/dynamic-cli pull request #98
Opened 2021-05-24 18:49 UTC by NamamiShanker

## Related Issue
- Get token from Notion.so login
- We still need to find a way to upload playbook content to Notion.so using this token.

## Describe the changes you've made
Added `settings.py` file to contain global variables and setting file paths. Added user login feature which will allow you to get token from user login through the browser. 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

2021-05-24 19:02 UTC, GouravSardana commented
Add some screenshots as well, If possible

2021-05-24 19:03 UTC, GouravSardana commented
@guptaaastha @pranavbaburaj You guys can also share your thoughts, If you want to change anything from your end or any improvement.

2021-05-24 19:40 UTC, NamamiShanker commented
I'm so tired of codacy

2021-05-24 19:49 UTC, NamamiShanker commented
> Add some screenshots as well, If possible

Added a GIF of working. Please help me fix this codacy issue.

2021-05-25 04:23 UTC, pranavbaburaj commented
I have resolved the codacy issues 🙂

2021-05-25 04:26 UTC, pranavbaburaj approved these changes
It looks good to me 🙂

2021-05-25 08:45 UTC, NamamiShanker commented
> I have resolved the codacy issues

Thank you so much!

2021-05-25 13:21 UTC, GouravSardana commented
After logged in. Does it say in ther terminal that login success or failure ?

2021-05-25 14:33 UTC, NamamiShanker commented
> After logged in. Does it say in the terminal that login success or failure ?

I'll add this

2021-05-25 15:53 UTC, NamamiShanker commented
@pranavbaburaj @GouravSardana Codacy keeps conflicting itself with Docstring styling. I have currently submitted the code in standard PEP8 notation with Sphinx rEST doc styling. Please see to the conflicts. I have also added Login Success and Failure messages.

2021-05-26 06:46 UTC, guptaaastha requested changes
@NamamiShanker everything looks fine, just add a login status' as follows
- Successfully logged into Notion 🎉 
- Unsuccessfull login. Please try again 😕 
(use emojis in the messages to be consistent and user friendly 😄 )

Also put a small explanation in the help message as to how to use this feature.
Adding a description in the documentation will also be helpful

2021-05-26 08:47 UTC, NamamiShanker commented
@guptaaastha I have made some changes. Added emojis in messages. Added entry in the documentation and put details in the help message.

2021-05-27 10:33 UTC, NamamiShanker commented
@pranavbaburaj @GouravSardana What do you guys suggest? Do I try to fix these Codacy warnings because it's conflicting with itself right now? Or do you guys prefer some changes?

2021-05-27 11:24 UTC, pranavbaburaj commented
![2021-05-27-16-52-github com](https://user-images.githubusercontent.com/70764593/119817845-15221500-bf0c-11eb-81da-62fca78378ca.png)
Hey @NamamiShanker, your branch is 12 commits behind the main branch. I recommend you to fetch and marge 🙂

2021-05-27 13:38 UTC, GouravSardana commented
Everything LGTM. @pranavbaburaj can you check the codacy issue with him or else I'll check it later today

2021-05-27 13:53 UTC, pranavbaburaj commented
> Everything LGTM. @pranavbaburaj can you check the codacy issue with him or else I'll check it later today

Sorry, I didn't understand what the issue is

2021-05-27 14:24 UTC, NamamiShanker commented
> Hey @NamamiShanker, your branch is 12 commits behind the main branch. I recommend you to fetch and marge.

@pranavbaburaj Yep! done.

2021-05-27 18:02 UTC, pranavbaburaj approved these changes
Looks good 👍🏾

2021-05-27 18:17 UTC, anshsrtv approved these changes
Great job! @NamamiShanker 🚀

2021-05-27 18:22 UTC, anshsrtv commented on src/arguments/error.py
> +        """Implements error printing for User Login
```suggestion
        """
        Implements error printing for User Login
```

2021-05-27 18:22 UTC, anshsrtv commented on src/arguments/notion.py
> +
```suggestion
```

2021-05-28 10:29 UTC, guptaaastha approved these changes
LGTM 
good work @NamamiShanker !

2021-05-28 10:30 UTC, guptaaastha commented
@NamamiShanker @pranavbaburaj Can you look into Codacy issues?
Checks are failing

2021-05-28 10:50 UTC, pranavbaburaj commented
> @NamamiShanker & @pranavbaburaj Can you look into Codacy issues?
> Checks are failing

Sorry @guptaaastha, I couldn't find the issues with codacy 😑

2021-05-28 11:24 UTC, NamamiShanker commented
> @NamamiShanker & @pranavbaburaj Can you look into Codacy issues?
> Checks are failing

Me neither. Don't understand why is it failing.

2021-05-28 12:04 UTC, guptaaastha commented
@GouravSardana @pranavbaburaj @NamamiShanker 
This thread seems related to the Codacy issue we're facing (D203) [https://github.com/PyCQA/pydocstyle/issues/141](https://github.com/PyCQA/pydocstyle/issues/141)
Have a look

2021-05-28 13:49 UTC, merged