Report issues using the command line
IndianOpenSourceFoundation/dynamic-cli pull request #99
Opened 2021-05-28 15:47 UTC by pranavbaburaj

- The new feature helps users to report issues with the application right from the command line
use 
`dynamic -i` to do so 

- I have also formatted all the files

2021-05-28 16:40 UTC, GouravSardana requested changes
@pranavbaburaj 

1. Paste one screenshot for reference while reporting the issue and how we can see the reported issues?
2. Why this .replit file is needed?
3. Can you check the codacy test? [1 blank line required before class docstring issues.py line 5]
4. Can we make a new folder of tests and move all the test files?

After this thing, we can set up Travis to run every time. So that nothing will break for the next time :)

2021-05-28 16:55 UTC, pranavbaburaj commented
> @pranavbaburaj
> 
> 1. Paste one screenshot for reference while reporting the issue and how we can see the reported issues?
> 2. Why this .replit file is needed?
> 3. Can you check the codacy test? [1 blank line required before class docstring issues.py line 5]
> 4. Can we make a new folder of tests and move all the test files?
> 
> After this thing, we can set up Travis to run every time. So that nothing will break for the next time :)

I will do all of these tomorrow morning. Thank you for the suggestions 👍🏾 . I forgot to add the `.replit` file into the gitignore 🤦🏾‍♂️

2021-05-29 16:59 UTC, Siddhant-K-code requested changes

2021-05-29 16:59 UTC, Siddhant-K-code commented on main.py
> +                    Resport an issue",
It should be "Report", I guess!

2021-05-29 16:59 UTC, Siddhant-K-code commented on .gitignore
> +.replit
Add EOF

2021-05-29 16:59 UTC, Siddhant-K-code commented on .replit
> +run = "python main.py -s"
add EOF

2021-05-30 05:42 UTC, pranavbaburaj commented
I think this pull request is irrelevant. I am closing this pull request. I will check out all the issues and work on some other issues

2021-06-06 12:38 UTC, pranavbaburaj commented
I reopened this pull request because it seemed to solve #105 . But, I have also added a small command that helps us to open the browser and report an issue.
```ps1
dynamic -i
```
This command will open up the browser with the issues tab.

2021-06-06 12:40 UTC, pranavbaburaj commented
I've checked out the issue again and I saw that @GouravSardana assigned the issue to @harshakhmk/ What do you guys suggest? Should I close this pull request ?

2021-06-06 12:41 UTC, closed without merging